apiVersion: v1
kind: Service
metadata:
  name: backend-dev
  namespace: support-chat-dev
  labels:
    app: support-chat
    component: backend
    env: dev
spec:
  type: ClusterIP
  selector:
    component: backend
    env: dev
  ports:
    - name: http
      port: 5000
      targetPort: 5000
