apiVersion: v1
kind: Service
metadata:
  name: backend-prod
  namespace: support-chat-prod
  labels:
    app: support-chat
    component: backend
    env: prod
spec:
  type: ClusterIP
  selector:
    component: backend
    env: prod
  ports:
    - name: http
      port: 5000
      targetPort: 5000
